//
// Created by y123456 on 2021/10/21.
//

#ifndef GAMEENGINE_VULKANDESCRIPTORSETLAYOUTBUILDER_H
#define GAMEENGINE_VULKANDESCRIPTORSETLAYOUTBUILDER_H



class VulkanDescriptorSetLayoutBuilder {

};



#endif //GAMEENGINE_VULKANDESCRIPTORSETLAYOUTBUILDER_H
